# Build the random C bot and the parity probe target.
#
# Only the ordinary conventions are honoured: CC, CFLAGS and LDFLAGS are picked
# up from the environment or the command line, and the recipe below simply adds
# to them. There is no dependency scanning, no generated header, no combine or
# export target yet; those come later, one stage at a time.

CC ?= cc
CFLAGS ?= -std=c11 -O2 -Wall -Wextra
LDFLAGS ?=

BUILD_DIR := build
BOT := $(BUILD_DIR)/c-random-bot
SOURCE := c/bot.c
# The neural bot includes the three local headers, and the generated model.h
# lives under runs/, which is git-ignored and regenerated by
# scripts/embed_nn_codebook.py. -lm is for expf in the network's sigmoid.
BOT_CFLAGS := -I runs/c-model-embedded
BOT_LDFLAGS := -lm
BOT_HEADERS := c/nn.h c/model_decode.h runs/c-model-embedded/model.h
NN_TEST := $(BUILD_DIR)/test-nn
NN_TEST_SOURCE := c/test_nn.c
NN_TEST_HEADER := c/nn.h
NN_COMPARE := $(BUILD_DIR)/test-nn-compare
NN_COMPARE_SOURCE := c/test_nn_compare.c
NN_EMBEDDED := $(BUILD_DIR)/test-nn-embedded
NN_EMBEDDED_SOURCE := c/test_nn_embedded.c
NN_DECODE_HEADER := c/model_decode.h
# The generated model.h lives under runs/, which is git-ignored and regenerated
# by scripts/embed_nn_codebook.py, so its directory is on the include path.
NN_EMBEDDED_INCLUDE := -I runs/c-model-embedded

# Sanitizer build for the header's smoke driver only. -O1 keeps frames and
# symbols readable while still exercising real code, and -fno-omit-frame-pointer
# is what gives the sanitizers usable stack traces.
NN_TEST_CFLAGS := -std=c11 -O1 -g -Wall -Wextra \
	-fsanitize=address,undefined -fno-omit-frame-pointer
NN_TEST_LDFLAGS := -fsanitize=address,undefined -lm

.PHONY: all bot test-nn test-nn-compare test-nn-embedded clean

all: bot

bot: $(BOT)

$(BOT): $(SOURCE) $(BOT_HEADERS) | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(BOT_CFLAGS) -o $@ $(SOURCE) $(LDFLAGS) $(BOT_LDFLAGS)

# Builds the driver only; running it is a separate, explicit step.
test-nn: $(NN_TEST)

$(NN_TEST): $(NN_TEST_SOURCE) $(NN_TEST_HEADER) | $(BUILD_DIR)
	$(CC) $(NN_TEST_CFLAGS) -o $@ $(NN_TEST_SOURCE) $(NN_TEST_LDFLAGS)

# Blob/CSV comparison rig. Builds only; running it is a separate, explicit step
# that needs an exported blob and a reference corpus.
test-nn-compare: $(NN_COMPARE)

$(NN_COMPARE): $(NN_COMPARE_SOURCE) $(NN_TEST_HEADER) | $(BUILD_DIR)
	$(CC) $(NN_TEST_CFLAGS) -o $@ $(NN_COMPARE_SOURCE) $(NN_TEST_LDFLAGS)

# Reconstructs the model from the embedded Base64 header and compares the bytes
# with an existing reference blob. Builds only; running it needs that reference.
test-nn-embedded: $(NN_EMBEDDED)

$(NN_EMBEDDED): $(NN_EMBEDDED_SOURCE) $(NN_DECODE_HEADER) $(NN_TEST_HEADER) \
		runs/c-model-embedded/model.h | $(BUILD_DIR)
	$(CC) $(NN_TEST_CFLAGS) $(NN_EMBEDDED_INCLUDE) -o $@ $(NN_EMBEDDED_SOURCE) \
		$(NN_TEST_LDFLAGS)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -f $(BOT) $(NN_TEST) $(NN_COMPARE) $(NN_EMBEDDED)
