#!/usr/bin/env python3
"""Embed a quantized codebook and index blob into a C header as Base64.

Command line::

    venv/bin/python scripts/embed_nn_codebook.py --codebook PATH \\
        --indices PATH --output-dir DIR

Inputs are the two quantized files from ``scripts/quantize_nn_blob.py``:

- ``codebook.bin`` — 256 little-endian float32 centers, 1,024 bytes;
- ``indices.bin`` — 49,537 uint8 nearest-center indices in original parameter
  order.

The payload is exactly those bytes concatenated: codebook first, then indices,
no header and no padding, 50,561 bytes. It is Base64 **encoded only**. There is
no compression of any kind here and no decompression stage: the C decoder that
would consume this is a later step. Base64 is chosen because it survives being
pasted into a C string literal as plain ASCII.

Outputs under ``--output-dir``:

- ``model.h`` — a guarded C header with the lengths, two CRC32 checksums and the
  payload as adjacent quoted 120-character chunks in a ``static const char``
  array. The character count excludes the terminating NUL.
- ``embedding-summary.txt`` — source paths, sizes, lengths and both checksums.

The decoded checksum is the canonical reconstruction: the stored codebook read
as 256 little-endian float32 values, the indices expanded in original order,
written back as little-endian float32 bytes. That is what makes the embedded
payload verifiable against the existing reconstructed ``model.bin`` without
changing any float, center or label. CRC32 is the standard unsigned 32-bit
``zlib.crc32`` over the payload bytes and, separately, over the reconstructed
float bytes.

The whole generated header must fit 75,000 characters, which the script checks
and enforces.
"""

import argparse
import base64
import sys
import zlib
from pathlib import Path

import numpy as np

CODEBOOK_VALUES = 256
CODEBOOK_BYTES = CODEBOOK_VALUES * 4
PARAMETER_COUNT = 49537
INDEX_BYTES = PARAMETER_COUNT
PAYLOAD_BYTES = CODEBOOK_BYTES + INDEX_BYTES
DECODED_BYTES = PARAMETER_COUNT * 4
BASE64_LENGTH = 4 * -(-PAYLOAD_BYTES // 3)
CHUNK_CHARS = 120
HEADER_CHAR_LIMIT = 75000

FLOAT_DTYPE = np.dtype('<f4')

HEADER_NAME = 'model.h'
SUMMARY_NAME = 'embedding-summary.txt'


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        prog='python scripts/embed_nn_codebook.py',
        description='Embed a codebook and index blob into a C header as Base64 '
                    'text, with CRC32 checksums. No compression.',
    )
    parser.add_argument('--codebook', required=True, type=Path, metavar='PATH',
                        help='codebook.bin: 256 little-endian float32 centers')
    parser.add_argument('--indices', required=True, type=Path, metavar='PATH',
                        help='indices.bin: 49537 uint8 indices, original order')
    parser.add_argument('--output-dir', required=True, type=Path, metavar='DIR',
                        help='directory receiving model.h and the summary')
    return parser.parse_args(argv)


def read_exact(path, expected_bytes, what):
    """Return the file's bytes, rejecting any other size."""
    resolved = path.expanduser().resolve()
    if not resolved.is_file():
        raise ValueError('%s does not exist: %s' % (what, resolved))
    data = resolved.read_bytes()
    if len(data) != expected_bytes:
        raise ValueError('%s is %s with %d bytes, expected %d'
                         % (what, resolved, len(data), expected_bytes))
    return resolved, data


def reconstruct_fp32_bytes(codebook_bytes, index_bytes):
    """Return the canonical expanded little-endian float32 bytes."""
    centers = np.frombuffer(codebook_bytes, dtype=FLOAT_DTYPE)
    if centers.size != CODEBOOK_VALUES:
        raise ValueError('codebook holds %d float32 values, expected %d'
                         % (centers.size, CODEBOOK_VALUES))
    indices = np.frombuffer(index_bytes, dtype=np.uint8)
    if indices.size != PARAMETER_COUNT:
        raise ValueError('indices hold %d values, expected %d'
                         % (indices.size, PARAMETER_COUNT))
    expanded = np.asarray(centers, dtype=FLOAT_DTYPE)[indices.astype(np.int64)]
    return np.ascontiguousarray(expanded, dtype=FLOAT_DTYPE).tobytes()


def quoted_chunks(encoded):
    """Return *encoded* as quoted C string chunks of at most 120 characters."""
    lines = []
    for start in range(0, len(encoded), CHUNK_CHARS):
        lines.append('    "%s"' % encoded[start:start + CHUNK_CHARS])
    return lines


def render_header(codebook_path, indices_path, encoded, payload_crc,
                  decoded_crc):
    """Return the complete model.h text."""
    lines = [
        '/* Generated by scripts/embed_nn_codebook.py on 2026-10-01.',
        ' * Do not edit by hand: regenerate from the codebook and indices.',
        ' *',
        ' * Payload layout, concatenated with no header and no padding:',
        ' *   bytes      0 .. 1023  codebook, 256 little-endian IEEE754 binary32',
        ' *                          (float32) centers',
        ' *   bytes   1024 .. 50560  indices, %d uint8 values in original'
        % PARAMETER_COUNT,
        ' *                          parameter order',
        ' *',
        ' * Decoding the Base64 below yields exactly %d bytes. Interpreting the'
        % PAYLOAD_BYTES,
        ' * codebook as %d little-endian float32 values and expanding each index'
        % CODEBOOK_VALUES,
        ' * to that center, in order, yields the canonical reconstruction of'
        ' %d' % DECODED_BYTES,
        ' * little-endian float32 bytes, whose CRC32 is the decoded checksum.',
        ' *',
        ' * Base64 is an encoding only. Nothing here is compressed.',
        ' *',
        ' * Sources:',
        ' *   codebook: %s' % codebook_path,
        ' *   indices:  %s' % indices_path,
        ' */',
        '',
        '#ifndef MODEL_H',
        '#define MODEL_H',
        '',
        '#include <stdint.h>',
        '',
        '#define MODEL_CODEBOOK_COUNT %du' % CODEBOOK_VALUES,
        '#define MODEL_PARAMETER_COUNT %du' % PARAMETER_COUNT,
        '#define MODEL_PAYLOAD_BYTES %du' % PAYLOAD_BYTES,
        '#define MODEL_DECODED_BYTES %du' % DECODED_BYTES,
        '#define MODEL_BASE64_LENGTH %du' % BASE64_LENGTH,
        '',
        '/* CRC32 (IEEE, zlib.crc32) of the %d payload bytes.' % PAYLOAD_BYTES,
        ' * Checked after Base64 decoding. */',
        '#define MODEL_PAYLOAD_CRC32 UINT32_C(0x%08x)' % payload_crc,
        '',
        '/* CRC32 (IEEE, zlib.crc32) of the %d reconstructed float32 bytes.'
        % DECODED_BYTES,
        ' * Checked after expanding the indices. */',
        '#define MODEL_DECODED_CRC32 UINT32_C(0x%08x)' % decoded_crc,
        '',
        '/* %d Base64 characters, excluding the terminating NUL. */'
        % BASE64_LENGTH,
        'static const char model_base64[] =',
    ]
    lines += quoted_chunks(encoded)
    lines += [
        '    ;',
        '',
        '#endif /* MODEL_H */',
        '',
    ]
    return '\n'.join(lines)


def embed(codebook_path, indices_path, output_dir):
    """Write model.h and embedding-summary.txt; return a result dict."""
    resolved_codebook, codebook_bytes = read_exact(
        codebook_path, CODEBOOK_BYTES, 'codebook')
    resolved_indices, index_bytes = read_exact(
        indices_path, INDEX_BYTES, 'indices')

    payload = codebook_bytes + index_bytes
    if len(payload) != PAYLOAD_BYTES:
        raise ValueError('payload is %d bytes, expected %d'
                         % (len(payload), PAYLOAD_BYTES))

    decoded_bytes = reconstruct_fp32_bytes(codebook_bytes, index_bytes)
    if len(decoded_bytes) != DECODED_BYTES:
        raise ValueError('reconstruction is %d bytes, expected %d'
                         % (len(decoded_bytes), DECODED_BYTES))

    encoded = base64.b64encode(payload).decode('ascii')
    if len(encoded) != BASE64_LENGTH:
        raise ValueError('Base64 text is %d characters, expected %d'
                         % (len(encoded), BASE64_LENGTH))

    payload_crc = zlib.crc32(payload) & 0xffffffff
    decoded_crc = zlib.crc32(decoded_bytes) & 0xffffffff

    header_text = render_header(resolved_codebook, resolved_indices, encoded,
                                payload_crc, decoded_crc)
    if len(header_text) > HEADER_CHAR_LIMIT:
        raise ValueError('generated header is %d characters, over the %d limit'
                         % (len(header_text), HEADER_CHAR_LIMIT))

    output_dir = output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    header_path = output_dir / HEADER_NAME
    header_path.write_text(header_text, encoding='ascii')

    summary_path = output_dir / SUMMARY_NAME
    summary = [
        'Othello Base64 header embedding',
        '==============================',
        '',
        'source codebook: %s (%d bytes)' % (resolved_codebook, CODEBOOK_BYTES),
        'source indices: %s (%d bytes)' % (resolved_indices, INDEX_BYTES),
        'payload bytes: %d (codebook then indices, no header or padding)'
        % PAYLOAD_BYTES,
        'base64 characters: %d (excluding the terminating NUL)' % BASE64_LENGTH,
        'base64 chunk characters: %d, last chunk shorter' % CHUNK_CHARS,
        'reconstructed float32 bytes: %d' % DECODED_BYTES,
        'payload CRC32: 0x%08x' % payload_crc,
        'decoded CRC32: 0x%08x' % decoded_crc,
        'crc32: standard unsigned 32-bit zlib.crc32, no compression applied',
        '',
        'header: %s' % header_path,
        'header characters: %d (limit %d)'
        % (len(header_text), HEADER_CHAR_LIMIT),
        'header bytes on disk: %d' % header_path.stat().st_size,
        'encoding: Base64 only, plain ASCII, no compression',
    ]
    summary_path.write_text('\n'.join(summary) + '\n', encoding='utf-8')

    return {
        'header_path': header_path,
        'summary_path': summary_path,
        'header_characters': len(header_text),
        'header_bytes': header_path.stat().st_size,
        'encoded_length': len(encoded),
        'payload_crc': payload_crc,
        'decoded_crc': decoded_crc,
        'decoded_bytes': decoded_bytes,
        'payload': payload,
        'encoded': encoded,
    }


def main(argv=None):
    args = parse_args(argv)
    try:
        result = embed(args.codebook, args.indices, args.output_dir)
    except (ValueError, OSError) as exc:
        print('embedding failed: %s' % exc, file=sys.stderr)
        return 1
    print('wrote %s' % result['header_path'])
    print('  header characters: %d (limit %d)'
          % (result['header_characters'], HEADER_CHAR_LIMIT))
    print('  base64 characters: %d' % result['encoded_length'])
    print('  payload CRC32: 0x%08x' % result['payload_crc'])
    print('  decoded CRC32: 0x%08x' % result['decoded_crc'])
    print('wrote %s' % result['summary_path'])
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
